/* AUTO-GENERATED by scripts/build_snapshot.py — do not edit by hand. */
window.LEO_DATA = window.LEO_DATA || {};
Object.assign(window.LEO_DATA, {
  "meta": {
    "version": "v5-h256-s30-g2.0",
    "n_features": 43,
    "best_val_loss": 0.21065215,
    "total_time_sec": 4558.33,
    "n_epochs": 30
  },
  "lstm": {
    "avg_auc": 0.8201648934705119,
    "avg_pr_auc": 0.5383354804462924,
    "per_horizon": {
      "h1": {
        "auc": 0.8372931185911248,
        "pr_auc": 0.5763087032642653,
        "p100": 1.0
      },
      "h5": {
        "auc": 0.8140270405232344,
        "pr_auc": 0.5253955807348866,
        "p100": 1.0
      },
      "h15": {
        "auc": 0.8091745212971766,
        "pr_auc": 0.5133021573397253,
        "p100": 1.0
      }
    },
    "train_losses": [
      0.221683,
      0.217851,
      0.216964,
      0.216541,
      0.215792,
      0.214845,
      0.214414,
      0.214239,
      0.214104,
      0.214104,
      0.213978,
      0.213981,
      0.213184,
      0.213072,
      0.213063,
      0.213017,
      0.212971,
      0.212495,
      0.21246,
      0.212435,
      0.212431,
      0.212365,
      0.212386,
      0.212092,
      0.212034,
      0.212029,
      0.212051,
      0.212025,
      0.212004,
      0.21184
    ],
    "val_losses": [
      0.21862,
      0.216368,
      0.215711,
      0.215109,
      0.213629,
      0.213312,
      0.212813,
      0.212923,
      0.212424,
      0.212707,
      0.213242,
      0.212836,
      0.211948,
      0.211575,
      0.211695,
      0.211965,
      0.211853,
      0.211321,
      0.211236,
      0.211066,
      0.21118,
      0.211155,
      0.21118,
      0.210863,
      0.210855,
      0.210822,
      0.210921,
      0.210855,
      0.210865,
      0.210652
    ]
  },
  "conformal": {
    "target_coverage": 0.9,
    "alpha": 0.1,
    "cal_sequences": 155337,
    "avg_coverage": 0.9011,
    "avg_width": 0.9915,
    "all_pass": false,
    "per_horizon": {
      "h1": {
        "q_hat": 0.519451,
        "coverage": 0.9025,
        "width": 0.9905,
        "status": "PASS"
      },
      "h5": {
        "q_hat": 0.52068,
        "coverage": 0.9009,
        "width": 0.9909,
        "status": "PASS"
      },
      "h15": {
        "q_hat": 0.525773,
        "coverage": 0.8998,
        "width": 0.9929,
        "status": "FAIL"
      }
    }
  },
  "agent": {
    "n_transactions": 10000,
    "proactive": {
      "failures": 731,
      "rate": 0.0731,
      "switches": 1140,
      "latency": 0.2791,
      "cost_1k": 109650.0,
      "retry": 7593,
      "normal": 1267,
      "switch": 1140
    },
    "reactive": {
      "failures": 1525,
      "rate": 0.1525,
      "switches": 1472,
      "latency": 0.1686,
      "cost_1k": 228750.0,
      "normal": 8528,
      "switch": 1472
    },
    "comparison": {
      "fail_reduction_pct": 52.07,
      "annual_savings": 3096600.0,
      "failures_avoided": 20644.0
    },
    "assumptions": {
      "cost_per_failure": 150.0,
      "tx_per_year": 260000,
      "high_risk": 0.55,
      "low_risk": 0.35,
      "lat_normal": 0.12,
      "lat_retry": 0.28,
      "lat_switch": 0.45
    }
  },
  "selfheal": [
    {
      "run_id": "20260316_175142",
      "timestamp": "2026-03-16T17:51:42",
      "mode": "dry_run",
      "rows": 42500,
      "failure_rate": 0.0,
      "drift_detected": false,
      "imbalance": true,
      "signals": {
        "error_rate_rolling": {
          "ks": 0.0,
          "p": 1.0,
          "drifted": false
        },
        "response_time_rolling_mean": {
          "ks": 0.0303,
          "p": 0.0,
          "drifted": false
        },
        "rt_multiplier": {
          "ks": 0.0051,
          "p": 0.945274,
          "drifted": false
        },
        "error_rate_boost": {
          "ks": 0.0,
          "p": 1.0,
          "drifted": false
        },
        "error_volatility": {
          "ks": 0.0,
          "p": 1.0,
          "drifted": false
        }
      },
      "model_updated": false,
      "delta": null
    },
    {
      "run_id": "20260316_175311",
      "timestamp": "2026-03-16T17:53:11",
      "mode": "dry_run",
      "rows": 255000,
      "failure_rate": 0.0007529411764706229,
      "drift_detected": false,
      "imbalance": true,
      "signals": {
        "error_rate_rolling": {
          "ks": 0.0496,
          "p": 0.0,
          "drifted": false
        },
        "response_time_rolling_mean": {
          "ks": 0.3226,
          "p": 0.0,
          "drifted": true
        },
        "rt_multiplier": {
          "ks": 0.048,
          "p": 0.0,
          "drifted": false
        },
        "error_rate_boost": {
          "ks": 0.0032,
          "p": 0.520645,
          "drifted": false
        },
        "error_volatility": {
          "ks": 0.0285,
          "p": 0.0,
          "drifted": false
        }
      },
      "model_updated": false,
      "delta": null
    },
    {
      "run_id": "20260316_175406",
      "timestamp": "2026-03-16T17:54:06",
      "mode": "dry_run",
      "rows": 170000,
      "failure_rate": 0.0,
      "drift_detected": false,
      "imbalance": true,
      "signals": {
        "error_rate_rolling": {
          "ks": 0.0,
          "p": 1.0,
          "drifted": false
        },
        "response_time_rolling_mean": {
          "ks": 0.0311,
          "p": 0.0,
          "drifted": false
        },
        "rt_multiplier": {
          "ks": 0.0021,
          "p": 0.993105,
          "drifted": false
        },
        "error_rate_boost": {
          "ks": 0.0,
          "p": 1.0,
          "drifted": false
        },
        "error_volatility": {
          "ks": 0.0,
          "p": 1.0,
          "drifted": false
        }
      },
      "model_updated": false,
      "delta": null
    },
    {
      "run_id": "20260316_175840",
      "timestamp": "2026-03-16T17:58:40",
      "mode": "dry_run",
      "rows": 170000,
      "failure_rate": 0.0,
      "drift_detected": false,
      "imbalance": true,
      "signals": {
        "error_rate_rolling": {
          "ks": 0.0,
          "p": 1.0,
          "drifted": false
        },
        "response_time_rolling_mean": {
          "ks": 0.0311,
          "p": 0.0,
          "drifted": false
        },
        "rt_multiplier": {
          "ks": 0.0021,
          "p": 0.993105,
          "drifted": false
        },
        "error_rate_boost": {
          "ks": 0.0,
          "p": 1.0,
          "drifted": false
        },
        "error_volatility": {
          "ks": 0.0,
          "p": 1.0,
          "drifted": false
        }
      },
      "model_updated": false,
      "delta": null
    },
    {
      "run_id": "20260316_180449",
      "timestamp": "2026-03-16T18:04:49",
      "mode": "dry_run",
      "rows": 170000,
      "failure_rate": 0.0059941176470588164,
      "drift_detected": false,
      "imbalance": true,
      "signals": {
        "error_rate_rolling": {
          "ks": 0.0009,
          "p": 1.0,
          "drifted": false
        },
        "response_time_rolling_mean": {
          "ks": 0.0028,
          "p": 0.90323,
          "drifted": false
        },
        "rt_multiplier": {
          "ks": 0.0037,
          "p": 0.598272,
          "drifted": false
        },
        "error_rate_boost": {
          "ks": 0.0006,
          "p": 1.0,
          "drifted": false
        },
        "error_volatility": {
          "ks": 0.001,
          "p": 1.0,
          "drifted": false
        }
      },
      "model_updated": false,
      "delta": null
    },
    {
      "run_id": "20260316_182334",
      "timestamp": "2026-03-16T18:23:34",
      "mode": "full",
      "rows": 170000,
      "failure_rate": 0.0059941176470588164,
      "drift_detected": false,
      "imbalance": true,
      "signals": {
        "error_rate_rolling": {
          "ks": 0.0009,
          "p": 1.0,
          "drifted": false
        },
        "response_time_rolling_mean": {
          "ks": 0.0028,
          "p": 0.90323,
          "drifted": false
        },
        "rt_multiplier": {
          "ks": 0.0037,
          "p": 0.598272,
          "drifted": false
        },
        "error_rate_boost": {
          "ks": 0.0006,
          "p": 1.0,
          "drifted": false
        },
        "error_volatility": {
          "ks": 0.001,
          "p": 1.0,
          "drifted": false
        }
      },
      "model_updated": false,
      "delta": -0.005277
    },
    {
      "run_id": "20260316_184228",
      "timestamp": "2026-03-16T18:42:28",
      "mode": "dry_run",
      "rows": 850000,
      "failure_rate": 0.025718823529411794,
      "drift_detected": true,
      "imbalance": true,
      "signals": {
        "error_rate_rolling": {
          "ks": 0.2508,
          "p": 0.0,
          "drifted": true
        },
        "response_time_rolling_mean": {
          "ks": 0.0663,
          "p": 0.0,
          "drifted": false
        },
        "rt_multiplier": {
          "ks": 0.0872,
          "p": 0.0,
          "drifted": false
        },
        "error_rate_boost": {
          "ks": 0.0148,
          "p": 0.0,
          "drifted": false
        },
        "error_volatility": {
          "ks": 0.2412,
          "p": 0.0,
          "drifted": true
        }
      },
      "model_updated": false,
      "delta": null
    },
    {
      "run_id": "20260318_212631",
      "timestamp": "2026-03-18T21:26:31",
      "mode": "dry_run",
      "rows": 170000,
      "failure_rate": 0.0059941176470588164,
      "drift_detected": false,
      "imbalance": true,
      "signals": {
        "error_rate_rolling": {
          "ks": 0.0009,
          "p": 1.0,
          "drifted": false
        },
        "response_time_rolling_mean": {
          "ks": 0.0028,
          "p": 0.90323,
          "drifted": false
        },
        "rt_multiplier": {
          "ks": 0.0037,
          "p": 0.598272,
          "drifted": false
        },
        "error_rate_boost": {
          "ks": 0.0006,
          "p": 1.0,
          "drifted": false
        },
        "error_volatility": {
          "ks": 0.001,
          "p": 1.0,
          "drifted": false
        }
      },
      "model_updated": false,
      "delta": null
    },
    {
      "run_id": "20260323_114635",
      "timestamp": "2026-03-23T11:46:35",
      "mode": "full",
      "rows": 850000,
      "failure_rate": 0.13750941176470588,
      "drift_detected": true,
      "imbalance": false,
      "signals": {
        "error_rate_rolling": {
          "ks": 0.6633,
          "p": 0.0,
          "drifted": true
        },
        "response_time_rolling_mean": {
          "ks": 0.1714,
          "p": 0.0,
          "drifted": true
        },
        "rt_multiplier": {
          "ks": 0.234,
          "p": 0.0,
          "drifted": true
        },
        "error_rate_boost": {
          "ks": 0.0281,
          "p": 0.0,
          "drifted": false
        },
        "error_volatility": {
          "ks": 0.6421,
          "p": 0.0,
          "drifted": true
        }
      },
      "model_updated": false,
      "delta": -0.016944
    },
    {
      "run_id": "20260324_120557",
      "timestamp": "2026-03-24T12:05:57",
      "mode": "full",
      "rows": 850000,
      "failure_rate": 0.2361352941176471,
      "drift_detected": true,
      "imbalance": false,
      "signals": {
        "error_rate_rolling": {
          "ks": 0.1845,
          "p": 0.0,
          "drifted": true
        },
        "response_time_rolling_mean": {
          "ks": 0.2154,
          "p": 0.0,
          "drifted": true
        },
        "rt_multiplier": {
          "ks": 0.014,
          "p": 0.0,
          "drifted": false
        },
        "error_rate_boost": {
          "ks": 0.0156,
          "p": 0.0,
          "drifted": false
        },
        "error_volatility": {
          "ks": 0.2513,
          "p": 0.0,
          "drifted": true
        }
      },
      "model_updated": false,
      "delta": -0.013454
    },
    {
      "run_id": "20260324_193405",
      "timestamp": "2026-03-24T19:34:05",
      "mode": "full",
      "rows": 1649534,
      "failure_rate": 0.17960042048239078,
      "drift_detected": true,
      "imbalance": false,
      "signals": {
        "error_rate_rolling": {
          "ks": 0.2354,
          "p": 0.0,
          "drifted": true
        },
        "response_time_rolling_mean": {
          "ks": 0.7617,
          "p": 0.0,
          "drifted": true
        },
        "rt_multiplier": {
          "ks": 0.2335,
          "p": 0.0,
          "drifted": true
        },
        "error_rate_boost": {
          "ks": 0.0378,
          "p": 0.0,
          "drifted": false
        },
        "error_volatility": {
          "ks": 0.1257,
          "p": 0.0,
          "drifted": true
        }
      },
      "model_updated": false,
      "delta": -0.041409
    }
  ],
  "ablation": {
    "baseline_auc": 0.852171,
    "experiments": [
      {
        "name": "Baseline",
        "auc": 0.852171,
        "n": 43,
        "base": true
      },
      {
        "name": "No Event Signals",
        "auc": 0.851768,
        "n": 41
      },
      {
        "name": "No Rolling Stats",
        "auc": 0.852661,
        "n": 38
      },
      {
        "name": "No Lag Features",
        "auc": 0.852785,
        "n": 40
      },
      {
        "name": "No EMA Features",
        "auc": 0.852147,
        "n": 40
      },
      {
        "name": "No Cyclical Enc.",
        "auc": 0.851748,
        "n": 39
      },
      {
        "name": "No API Flags",
        "auc": 0.852548,
        "n": 41
      },
      {
        "name": "No Precursor Signals",
        "auc": 0.852241,
        "n": 32
      },
      {
        "name": "No Cross-API",
        "auc": 0.851496,
        "n": 38
      }
    ]
  }
});

window.LEO_DATA.dataset = window.LEO_DATA.dataset || {
  rows: 1220008,
  failure_rate: 0.1388,
  apis: [
    { name: "transaction_api", share: 0.25,   color: "#dc2626" },
    { name: "market_data_api", share: 0.25,   color: "#fbbf24" },
    { name: "stock_price_api", share: 0.103,  color: "#f59e0b" },
    { name: "crypto_api",      share: 0.104,  color: "#84cc16" },
    { name: "forex_api",       share: 0.104,  color: "#ea580c" },
    { name: "other",           share: 0.189,  color: "#fcd34d" }
  ],
  date_range: "2023-01-01 → 2024-12-31"
};
